var message = "Muskan would you like to learn some typscript?";
console.log(message);
var person_name = "Muskan";
console.log(person_name);
var num = 89;
var bool = 7 != 7;
var array = ["muskan", 89, false, true];
var array2 = ["muskan", "areeba", "hassan"];
var array3 = [8, 90, 23, 45, 7];
var array4 = [true, false, true, false];
var array5 = [89, 90, 78, true, false, true];
